name: Eblen Construction
favicon: null
layout_spectrum: 0.6920267324894667
typography_spectrum: 0.2373000718653202
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5187929237727076
  lightness: 0.733037207974121
  saturation: 0.7137651338707656
  rhythmicContrast: 0.30124835297465324
purpose: []
